### ISSUE TITLE
Yesterday Scores

### ISSUE THREAD

**Issue by nealmick** [ynnadkrap/balldontlie#118]
Hello, thank you for all your work.
It appears as though game scores from yesterday are not updating. 
https://www.balldontlie.io/api/v1/games/972866

Also I believe the datetime status is reporting all games as 2023-05-12T04:00:00Z
https://www.balldontlie.io/api/v1/games?dates[]=2023-05-12

**Comment by bjplink** [comment]
I really love the API and I've been using it to run a simple bot on Mastodon (https://botsin.space/@nbascores) this season. Everything was very smooth until the postseason began.

Since the playoff started, I've also seen these two problems pop up. Occasionally, the final scores and stats after a game ends are either wrong or missing entirely. Start times have been incorrect for quite a while now as well.

**Comment by nealmick** [comment]
Yea I think the endpoints change fairly often during play-offs. 
Definitely a cool project on Mastodon too!
