### ISSUE TITLE
Missing today's game

### ISSUE THREAD

**Issue by nealmick** [ynnadkrap/balldontlie#119]
Hello noticed this morning api is reporting no games today.
https://www.balldontlie.io/api/v1/games?dates[]=2023-05-16

I believe there is one game today denver vs lakers.

**Comment by nealmick** [comment]
Still having trouble with today's game, any insight is greatly appreciated!

**Comment by jasonfrancki** [comment]
Looked into this further, when requesting game scores for specific dates via https://free-nba.p.rapidapi.com/games:

1. Final Score data has been missing for games since 5/11/23
2. Games have been inaccurate since 5/14 (returns 3 games instead of the 1 game that actually was played that day. 5/15 shows a game that was not actually played, and there are no games on any day after that)

**Comment by nealmick** [comment]
I noticed the same issues over the past few days.  I believe the endpoints change more often during post season.  Really appreciate this project and all of the work that goes into it, hoping for a fix before tonight's game :)

**Comment by nealmick** [comment]
bump issue, still no games :(

**Comment by nealmick** [comment]
all fixed, thanks a bunch!
